# Generated by Django 5.1 on 2024-09-14 18:06

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_perfil_options_perfil_city_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
    ]
