# Generated by Django 5.1 on 2024-09-17 13:37

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_perfil_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000,1,1)),
            preserve_default=False,
        ),
    ]
