# Generated by Django 5.1 on 2024-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_perfil_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
