# Generated by Django 5.1 on 2024-09-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_perfil_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='birth_date',
        ),
    ]
