# Generated by Django 5.1 on 2024-08-29 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuário', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quarto',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='cadastro_hotel.hotel'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastro_hotel.quarto'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='cadastro_hotel.quarto'),
        ),
        migrations.AddField(
            model_name='cancelamentoreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cancelamento', to='cadastro_hotel.reserva'),
        ),
    ]
