# Generated by Django 5.1 on 2024-09-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_hotel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='comodidade',
            new_name='comodidades',
        ),
    ]
