# Generated by Django 5.1 on 2024-09-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_hotel', '0003_rename_comodidade_hotel_comodidades'),
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reserva',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_reserva', to='cadastro_hotel.reserva'),
            preserve_default=False,
        ),
    ]
